from __future__ import print_function

import csv
import os

from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.utils import np_utils
from keras.callbacks import ReduceLROnPlateau, CSVLogger, EarlyStopping
from keras import backend as K

import numpy as np
import resnet


lr_reducer = ReduceLROnPlateau(factor=np.sqrt(0.1), cooldown=0, patience=5, min_lr=0.5e-6)
early_stopper = EarlyStopping(min_delta=0.001, patience=10)
csv_logger = CSVLogger('resnet18_cifar10.csv')

batch_size = 32
nb_classes = 10
nb_epoch = 10
data_augmentation = True

# input image dimensions
img_rows, img_cols = 32, 32
# The CIFAR10 images are RGB.
img_channels = 3

# The data, shuffled and split between train and test sets:
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

directory = 'C:\ProgrammingOriented//projects//mfml18//residual//layer_output//layer_0'

os.mkdir(directory)
with open('residual//layer_output//layer_' + str(0) + '//trainingData.txt', 'w', newline='') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=' ')
    for label in X_train:
        output = np.array(label).flatten()
        output -= output.min()
        output = output / (output.max())
        spamwriter.writerow(output)
with open('residual//layer_output//layer_' + str(0) + '//trainingLabel.txt', 'w', newline='') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=' ')
    for label in y_train:
        row = [0]*nb_classes
        row[label[0]] = 1
        spamwriter.writerow(row)
with open('residual//layer_output//layer_' + str(0) + '//testingData.txt', 'w', newline='') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=' ')
    for label in X_test:
        output = np.array(label).flatten()
        output -= output.min()
        output = output / (output.max())
        spamwriter.writerow(output)
with open('residual//layer_output//layer_' + str(0) + '//testingLabel.txt', 'w', newline='') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=' ')
    for label in y_test:
        row = [0] * nb_classes
        row[label[0]] = 1
        spamwriter.writerow(row)
# Convert class vectors to binary class matrices.
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# subtract mean and normalize
mean_image = np.mean(X_train, axis=0)
X_train -= mean_image
X_test -= mean_image
X_train /= 128.
X_test /= 128.

model = resnet.ResnetBuilder.build_resnet_18_mine((img_channels, img_rows, img_cols), nb_classes)
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

if not data_augmentation:
    print('Not using data augmentation.')
    model.fit(X_train, Y_train,
              batch_size=batch_size,
              nb_epoch=nb_epoch,
              validation_data=(X_test, Y_test),
              shuffle=True,
              callbacks=[lr_reducer, early_stopper, csv_logger])
else:
    print('Using real-time data augmentation.')
    # This will do preprocessing and realtime data augmentation:
    datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=True,  # randomly flip images
        vertical_flip=False)  # randomly flip images

    # Compute quantities required for featurewise normalization
    # (std, mean, and principal components if ZCA whitening is applied).
    datagen.fit(X_train)

    # Fit the model on the batches generated by datagen.flow().
    model.fit_generator(datagen.flow(X_train, Y_train, batch_size=batch_size),
                        steps_per_epoch=X_train.shape[0] // batch_size,
                        validation_data=(X_test, Y_test),
                        epochs=nb_epoch, verbose=1, max_q_size=100,
                        callbacks=[lr_reducer, early_stopper, csv_logger])

count = 0
for layer_index in range(1, len(model.layers), 1):
    directory = 'C:\ProgrammingOriented//projects//mfml18//residual//layer_output//layer_'+str(layer_index)
    try:
        os.stat(directory)
    except:
        os.mkdir(directory)

    get_k_layer_output = K.function([model.layers[0].input],
                                      [model.layers[layer_index].output])


    with open('residual//layer_output//layer_'+str(layer_index)+'//trainingData.txt', 'w') as csvfile:
        spamwriter = csv.writer(csvfile, delimiter=' ')
        for startingImageIndex in range(int(len(X_train) / 2)):
            sample = X_train[startingImageIndex:startingImageIndex + 2]
            layer_output = get_k_layer_output([sample])[0]
            for imageIndex in range(2):
                count += 1
                print(count)
                output = layer_output[imageIndex].flatten()
                output -= output.min()
                output = output/(output.max())
                print("number of features: " + str(len(output)))
                spamwriter.writerow(output)
    with open('residual//layer_output//layer_'+str(layer_index)+'//trainingLabel.txt', 'w') as csvfile:
        spamwriter = csv.writer(csvfile, delimiter=' ')
        for label in y_train:
            row = [0] * nb_classes
            row[label[0]] = 1
            spamwriter.writerow(row)
    with open('residual//layer_output//layer_'+str(layer_index)+'//testingData.txt', 'w') as csvfile:
        spamwriter = csv.writer(csvfile, delimiter=' ')
        for startingImageIndex in range(int(len(X_test) / 2)):
            sample = X_test[startingImageIndex:startingImageIndex + 2]
            layer_output = get_k_layer_output([sample])[0]
            for imageIndex in range(2):
                count += 1
                print(count)
                output = layer_output[imageIndex].flatten()
                output -= output.min()
                output = output/(output.max())
                print("number of features: " + str(len(output)))
                spamwriter.writerow(output)
    with open('residual//layer_output//layer_'+str(layer_index)+'//testingLabel.txt', 'w') as csvfile:
        spamwriter = csv.writer(csvfile, delimiter=' ')
        for label in y_test:
            row = [0] * nb_classes
            row[label[0]] = 1
            spamwriter.writerow(row)